const fs = require('fs')
fs.writeFileSync('./.env', 
`VITE_APP_CAPTCHATOKEN=${process.env.VITE_APP_CAPTCHATOKEN}\n
VITE_APP_EMAILJS_SERVICEID=${process.env.VITE_APP_EMAILJS_SERVICEID}\n
VITE_APP_EMAILJS_TEMPLATEID=${process.env.VITE_APP_EMAILJS_TEMPLATEID}\n
VITE_APP_CAPTCHATOKEN=${process.env.VITE_APP_CAPTCHATOKEN}\n
VITE_APP_EMAILJS_TOKEN=${process.env.VITE_APP_EMAILJS_TOKEN}\n
VITE_APP_EMAILJS_USERID=${process.env.VITE_APP_EMAILJS_USERID}\n`)
